# Generated by Django 3.2.6 on 2021-08-29 15:38

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('custom_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=240, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to=authentication.models.get_dp_path)),
                ('bio', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
