# Generated by Django 3.2.11 on 2022-04-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('comments_list', models.JSONField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='core.post')),
            ],
        ),
    ]
